services:
  db:
    image: 'postgres:latest'
    env_file:
      - secrets/postgres-example.env
    ports:
      - '5432:5432'
  app:
    image: t-bank:latest
    build:
      context: .
    restart: no
    env_file:
      - secrets/postgres-example.env
      - secrets/yandex.env
    environment:
      - 'POSTGRES_URL=jdbc:postgresql://db:5432/mydatabase'
    depends_on:
      - db
    ports:
      - "8080:8080"


